name: REvil_Warp

on:
  push:
    branches: [ "main" ]
    paths:
      - 'warp.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
    - name: Commit and push changes
      run: |          
          git config --global user.email "nyeinkokoaung1997@gmail.com"
          git config --global user.name "nyeinkokoaung404"
          git config credential.helper store
          git add -A
          git commit -m "Automatic update"
          git push
